# Generated by Django 2.1.2 on 2018-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('español', models.CharField(max_length=50)),
                ('portuges', models.CharField(max_length=50)),
                ('creolles', models.CharField(max_length=50)),
                ('ingles', models.CharField(max_length=50)),
            ],
        ),
    ]
